#!/bin/bash
cd build
meson configure -Dut='datastructure' -dutvalue='(~0x0040)'
ninja clean
ninja 

valgrind --undef-value-errors=no --tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=20 --track-fds=no --trace-syscalls=no\
   	./notstd
